import { ConnectButton } from "@rainbow-me/rainbowkit";
import Head from "next/head";
import Image from "next/image";
import Script from "next/script";

import styles from "../styles/Home.module.css";

export const YourApp = () => {
  return <ConnectButton />;
};

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Rainbowkit Starter</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js</a> +{" "}
          <a href="https://www.rainbowkit.com/">RainbowKit!</a>
        </h1>
        <h2 className={styles.title}>
        Template on <a href="https://github.com/launchweb3/rainbowkit/generate">Github</a> 🌈{" "}
        </h2>
        <h3> Maintained by LaunchWeb3</h3>

        <ConnectButton />
      </main>
    </div>
  );
}
